### ISSUE TITLE
[iOS] images aren't appearing

### ISSUE THREAD

**Issue by mgxd** [satra/voiceup-mdd#3]
Steps 1-4 don't have visible images, but clicking where they should be still makes numbers appear (1-5)

**Comment by sitek** [comment]
+1
although I didn't know where numbers should be, so I couldn't check that `clicking where they should be still makes numbers appear (1-5)`

**Comment by satra** [comment]
@sitek: do the images not appear on android?

**Comment by sitek** [comment]
correct, I'm on a Nexus 6 with Android 6.0.1

**Comment by sitek** [comment]
Also not appearing on Samsung Galaxy 4, Android 4.4.4 per @ysanchezaraujo

**Comment by satra** [comment]
@sitek - can you update to the latest version? i pushed an update that should technically fix this issue.

**Comment by satra** [comment]
ios is still waiting for review

**Comment by sitek** [comment]
beta update (app version 0.1.1) fixes this on android

**Comment by mgxd** [comment]
0.1.1 fixed steps 1-3, but step 4 (sleep) only showed images 1 and 5, the rest are still missing

**Comment by satra** [comment]
@mgxd - that's really weird. can you log back in? it should redownload the images.

@sitek - these images are coming from your github account, can you check if you have run into a bandwidth limitation there?

**Comment by mgxd** [comment]
@satra after redownloading images are present, I first signed in using spotty connection so it's possible the images didn't download properly

**Comment by satra** [comment]
i'll update the code so that it can find those images locally on the app if the consent asks for it.

**Comment by sitek** [comment]
@satra no issue so far, although on a basic account I haven't found a way to check bandwidth usage (but they seem to have a "be reasonable" guideline without hard limits)
